const ARTISTS = [
  {
    Id: 1,
    name: "ገርጂ ቤ/ን መዘምራን",
    genre: "የምጻት ዝማሬ",
    bio: "የገርጂ የመዘምራን ኳየር የተዘመረ መዝሙር ነው፡፡",
    imageUrl: "https://example.com/artist1.jpg",
    createdAt: "2025-09-05T11:43:36.555Z",
  },
  {
    Id: 2,
    name: "ተፈራ ወ/ማሪያም",
    genre: "የጸሎት መዝሙር",
    bio: "ተፈራ ወ/ማሪያም ብዙ አልበሞች ያሉት የድሮ የአድቬንትስት ዘማሪ ነው፡፡",
    imageUrl: "https://example.com/artist2.jpg",
    createdAt: "2025-09-05T11:43:36.575Z",
  },
  {
    Id: 3,
    name: "አለሙ ብላቱ",
    genre: "የጸሎት መዝሙር",
    bio: "አለሙ ብላቱ ብዙ አልበሞች ያሉት የድሮ የአድቬንትስት ዘማሪ ነው፡፡",
    imageUrl: "https://example.com/artist2.jpg",
    createdAt: "2025-09-05T11:43:36.577Z",
  },
  {
    Id: 4,
    name: "Gimbie C. Choir",
    genre: "የጸሎት መዝሙር",
    bio: "Gimbie C. Choir ብዙ አልበሞች ያሉት የድሮ የአድቬንትስት ዘማሪ ነው፡፡",
    imageUrl: "https://example.com/artist2.jpg",
    createdAt: "2025-09-05T11:43:36.578Z",
  },
  {
    Id: 5,
    name: "ተፈራ ወ/ማሪያም",
    genre: "የጸሎት መዝሙር",
    bio: "ተፈራ ወ/ማሪያም ብዙ አልበሞች ያሉት የድሮ የአድቬንትስት ዘማሪ ነው፡፡",
    imageUrl: "https://example.com/artist2.jpg",
    createdAt: "2025-09-05T14:00:11.637Z",
  },
  {
    Id: 6,
    name: "አለሙ ብላቱ",
    genre: "የጸሎት መዝሙር",
    bio: "አለሙ ብላቱ ብዙ አልበሞች ያሉት የድሮ የአድቬንትስት ዘማሪ ነው፡፡",
    imageUrl: "https://example.com/artist2.jpg",
    createdAt: "2025-09-05T14:00:11.638Z",
  },
  {
    Id: 7,
    name: "ጫኔ አለሙ",
    genre: "የጸሎት መዝሙር",
    bio: "ጫኔ አለሙ የአማርኛም አልበሞች ያሉት የአድቬንትስት ዘማሪ ነው፡፡",
    imageUrl: "https://example.com/artist2.jpg",
    createdAt: "2025-11-02T20:19:52.859Z",
  },
];
export default ARTISTS