 enum CATEGORIES {
  THANKSGIVING = "THANKSGIVING",
  CONFESS = "CONFESS",
  PRAISE = "PRAISE",
  PRAYER = "PRAYER",
  CHRISTIAN_LIVING = "CHRISTIAN_LIVING",
  DEVOTIONAL = "DEVOTIONAL",
  WORSHIP = "WORSHIP",
  TESTIMONY = "TESTIMONY",
  MISCELLANEOUS = "MISCELLANEOUS"
}
export default CATEGORIES